[package]
name = "rascam"
version = "0.0.1"
authors = ["Peter Sutherland <pedrosland+rascam@gmail.com>"]
description = "Library for taking photos and videos with the Raspberry Pi camera"
repository = "https://github.com/pedrosland/rascam"
documentation = "https://pedrosland.github.io/rascam/"
readme = "README.md"
license = "MIT"
categories = [ "hardware-support" ]
keywords = [ "camera", "raspberry", "pi", "rpi" ]
exclude = [ "ci/*" ]
build = "build.rs"

[dependencies]
mmal-sys = "0.1.0-1"
libc = "0.2"
parking_lot = {version = "0.5", features = ["nightly"]}
scopeguard = "0.3.3"

[features]
default = []

# Enable this feature to enable some print statements for debugging.
debug = []
