[package]
name = "cam"
version = "0.1.0"
authors = ["Pedro Sland <pedrosland@gmail.com>"]

[dependencies]
mmal-sys = { path = "mmal-sys" }
libc = "0.2"
futures = "0.1"
parking_lot = {version = "0.5", features = ["nightly"]}
scopeguard = "0.3.3"

[[bin]]
name = "test"
path = "src/main.rs"

[profile.dev]
# opt-level = 3
